### ISSUE TITLE
Location Object with string latitude and longitude values

### ISSUE THREAD

**Issue by akeranen** [OpenMobileAlliance/lwm2m-registry#257]
Current [Location object (3336)](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/test/3336.xml) uses string valued lat/long resources (5514 and 5515). It might make sense to rename those RRs to "String Latitude / Longitude" and register new RRs and Object using float values to align better with the [LwM2M Location object](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/test/LWM2M_Location-v1_0_2.xml).

Similar issue with the Uncertainty RR (5516); could be renamed "(String) Location Uncertainty".

**Comment by mkgillmore** [comment]
Need a new pull request that creates new RR's for latitude and longitude as float object types.

**Comment by mkgillmore** [comment]
@akeranen Ari,  have you made a pull request for this?  I will close this issue by 10/1/2020 if I do not see a proposal

**Comment by akeranen** [comment]
Can’t do one during my leave but it’s such an obvious problem that some fix should be done instead of ignoring this.

**Comment by jaimejim** [comment]
From the chat discussion I am not sure if this is exactly what you guys want. I just did a PR of a 3336 object with latitude, longitude and uncertainty as string and a new "decimal" latitude, longitude and uncertainty optional float resources. Incrementing object version to 1.2. I leave the OIDs with XXXX pending code number assignment.

https://github.com/OpenMobileAlliance/lwm2m-registry/pull/586

**Comment by jpradocueva** [comment]
@jaimejim it will be easier for us if we create the branch for you, rather than you create a PR directly against "test". IPSO has changed the branch to start the work to "dev". The reason to follow the instructions in https://github.com/OpenMobileAlliance/lwm2m-registry#lwm2m-registry is because it makes it easy to validate and merge the content without conflicts.
I will close the current PR and will create a new branch for you to apply these changes. In this way it will be easy to do the work.

**Comment by seanmcilroy29** [comment]
New branch create for the update to Obj - 3336 See - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/3336_update

**Comment by mkgillmore** [comment]
Group agreed to closed due to a pull request addressing the issue
