### ISSUE TITLE
/4/0/9 and /4/0/10 errata

### ISSUE THREAD

**Issue by will-aos** [OpenMobileAlliance/lwm2m-registry#518]
Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | /4/0/9 and /4/0/10 errata
Name of SDO, Company or individual    | Will Bell, Aetheros
Object Name (as defined in the .xml file) |  Object 4:  resource 9 SMNC and resource 10 SMCC
Short Object description, to be used in the pubic registry (max 134 characteres) | The integer data types for /4/0/9 and /4/0/10 are incorrect. Per 3GPP 23.003 the data types for both resources should be strings, to preserve the significant leading zeros when marshalled and unmarshalled.

**Comment by seanmcilroy29** [comment]
Comments submitted by DMSE WG

MCC is always 3 digit code.
MNC can be 2 or 3 digit code with a leading 0.

Changing from integer to string would cause backward incompatibility issues. We recommend the server-side applications to add leading zeroes when needed.

**Comment by will-aos** [comment]
@seanmcilroy29 
So you are proposing that the community live with this obvious bug forever?
Will the Working Group consider fixing the data type in a v.1.3 (or later) of object 4?
It is impractical to expect a server to understand when an MNC for example reported by client should be 10 or 010, both of which are valid and distinct values.

**Comment by hannestschofenig** [comment]
We will consider this change in the next major release but for version 1.2 we cannot change the data type from integer to string due to backwards compatibility problems.

**Comment by hannestschofenig** [comment]
FWIW we are always looking for experts, like yourself, to participate in the work and contribute text to make the changes to the specification. We encourage you to join OMA SpecWorks and to help us in the standardization process.

**Comment by jpradocueva** [comment]
If further discussion is needed on this topic, I suggest to create an issue here https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues. 

This discussion is about Object ID 4, Connectivity Monitoring and the protocol. This discussion should take place in the above repository rather than here. This repository is dedicated to register new Objects or discussion with Object created by OMA IPSO Working Group.

The topic is closed by the option to have further discussion is still possible in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues
