### ISSUE TITLE
On Remote SIM Provisioning proposed Objects (504, 505)

### ISSUE THREAD

**Issue by jaimejim** [OpenMobileAlliance/lwm2m-registry#607]
I would like to raise an issue on PRs [#606](https://github.com/OpenMobileAlliance/lwm2m-registry/pull/606) and [#604](https://github.com/OpenMobileAlliance/lwm2m-registry/pull/604), which are related to objects [504.xml](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/58361a9a7fba163f4d49d837126e5705bb24e4cb/504.xml) and [505.xml](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/84e4e1dbd67f4806f16b38b5788c0cd9a151bb51/505.xml)

My main concern is that there seems to be two objects for Remote SIM Provisioning (504 and 505). It seems 504 is a superset that includes 505. Would it not make more sense then to have just 504 instead of two objects?

Another comment is that while in DMSE there is no reusable Resource IDs, in IPSO we try -when possible- to keep reusable identifiers. It would be great if the authors could change that in the XML when relevant and register the Resource IDs.

**Comment by asoloway64** [comment]
We believe we have met the Ericsson desires by defining Object 504 to address the use case where the LwM2M client connects directly to the SM-DP+ server and the use case where the LwM2M server is an intermediary between the LwM2M client and the SM-DP+ server. Per the Qualcomm desire, the use case where the LwM2M server is the repository of the SIM Update Package and is used to download that package to the LwM2M client where the update SIM process is locally executed is addressed in Object 505.

There are enough differences in the similar resources such that they should evolve independently (usage, enumerated values, states, etc.) which is why separate objects are preferred.

In terms of reusable resources, there are some resources we could declare as reusable resources, but we did not see enough future use to merit the extra effort and we did follow the original DMSE style rather than the IPSO style . If you think there is enough value to separate certain resources into reusable resources, please let us know which ones and we will make that effort.

**Comment by PerStahl** [comment]
Thanks Alan. So the Qualcomm proposal is to modify Object 504 to remove support for nuSIM and focus only on GSMA Remote SIM Provisioning and the nuSIM provisioning would be handled by Object 505? We are fine with this approach but the naming of the objects must reflect this, which the current namings don’t. The users are fully aware whether they use GSMA eSIM or nuSIM. Hence, our proposal is to call Object 504 ”GSMA Remote SIM Provisioning” and Object 505 ”nuSIM Provisioning”.

**Comment by hannestschofenig** [comment]
Based on Object 504 and 505 in https://github.com/OpenMobileAlliance/lwm2m-registry/pull/606 and https://github.com/OpenMobileAlliance/lwm2m-registry/pull/604 this issue can be closed.

**Comment by mkgillmore** [comment]
Closed per 5/11/2021
